# -*- coding: utf-8 -*-
"""pets-classifier-deployment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16v2zt_BobphVF0cz4hGeNEUM9HinvlTS
"""
import gradio as gr
from fastai.vision.all import *

learn = load_learner('export.pkl')

labels = learn.dls.vocab
def predict(img):
    img = PILImage.create(img)
    pred, pred_idx, probs = learn.predict(img)
    return {labels[i]: float(probs[i]) for i in range(len(labels))}


title = "Pet Breed Classifier"
description = """A pet breed classifier trained on the Oxford Pets dataset with fastai.
                Created as a demo for Gradio and HuggingFace Spaces. """
interpretation = 'default'

demo2 = gr.Interface(fn=predict, inputs=gr.inputs.Image(shape=(512, 512)),
             outputs=gr.outputs.Label(num_top_classes=3),
                     title=title, description=description,
                     interpretation=interpretation)
demo2.launch(inline=False)